spring:
    profiles:
        active: dev
---
spring:
    profiles: dev
    datasource:
        url: jdbc:postgresql://localhost:5432/cooperative?createDatabaseIfNotExist=true
        username: newparus
        password: n3wp@rus
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
---
spring:
    profiles: deploy
    datasource:
        url: ${JDBC_DATARESOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        generate-dll: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true